# Generated by Django 2.1.3 on 2018-11-18 17:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=256)),
                ('tipIzdelka', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'pica'), (2, 'kruhek'), (3, 'kosilo'), (4, 'pijaca')], max_length=7)),
                ('velikost', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Otroška'), (2, 'Mala'), (3, 'Velika'), (4, 'Uni')], max_length=7)),
                ('sestavine', models.CharField(max_length=512)),
                ('alergeni', models.CharField(max_length=512)),
                ('slika', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('cenaOtroska', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cenaMala', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cenaVelika', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cenaUni', models.DecimalField(decimal_places=2, max_digits=3)),
                ('datum_kreiranja', models.DateField(auto_now_add=True)),
                ('prikazi', models.BooleanField(default=True)),
            ],
        ),
    ]
