# Generated by Django 2.1.3 on 2018-11-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=256)),
                ('tipmalice', models.CharField(choices=[(1, 'A'), (2, 'B')], default='A', max_length=1)),
                ('cena', models.IntegerField(default=5)),
                ('opis', models.TextField()),
            ],
        ),
    ]
