# Generated by Django 2.1.3 on 2018-11-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='malica',
            name='dan',
            field=models.CharField(choices=[(1, 'ponedeljek'), (2, 'torek'), (3, 'sreda'), (4, 'cetrtek'), (5, 'petek')], default='ponedeljek', max_length=20),
        ),
    ]
