# Generated by Django 2.1.3 on 2018-11-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malice', '0002_malica_dan'),
    ]

    operations = [
        migrations.AddField(
            model_name='malica',
            name='alergeni',
            field=models.CharField(default='vpis alergenov', max_length=256),
        ),
    ]
